/**
 * emojis.ts — Centralized AshenAI emoji registry
 *
 * Maps logical emoji names to Discord custom emoji format (<:name:id>).
 * Falls back to Unicode emoji when custom emoji IDs are not configured.
 *
 * Configuration lives in icons.ts — edit that file to change icon sources.
 * This module reads from it and provides the runtime emoji() API.
 *
 * Custom emoji IDs are read from environment variables or emoji-manifest.json.
 * To upload custom emojis, run: npm run upload:emojis
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  ICON_MAP,
  ICON_NAMES,
  LEGACY_TO_LOGICAL,
  type IconName,
  type LegacyEmojiName,
} from "./icons";

// ---------------------------------------------------------------------------
// Re-export types for backward compatibility
// ---------------------------------------------------------------------------

/** Legacy "ash_" prefixed name type — accepts both old and new formats */
export type EmojiName = LegacyEmojiName | IconName;

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

let _guildId: string | undefined;
let _resolvedIds: Partial<Record<IconName, string>> = {};
let _initialized = false;

function init(): void {
  if (_initialized) return;
  _initialized = true;

  // Read from environment variables
  for (const [name, config] of Object.entries(ICON_MAP)) {
    const id = process.env[config.envVar]?.trim();
    if (id) {
      _resolvedIds[name as IconName] = id;
    }
  }

  // Try to load from emoji-manifest.json (generated by upload script)
  try {
    const manifestPath = join(process.cwd(), "assets", "emojis", "emoji-manifest.json");
    if (existsSync(manifestPath)) {
      const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
      if (manifest.guildId && !_guildId) {
        _guildId = manifest.guildId;
      }
      if (manifest.emojis && typeof manifest.emojis === "object") {
        for (const [legacyName, id] of Object.entries(manifest.emojis)) {
          if (typeof id === "string") {
            // Support both legacy "ash_*" and new logical names
            const logical = LEGACY_TO_LOGICAL[legacyName as LegacyEmojiName]
              ?? (ICON_NAMES.includes(legacyName as IconName) ? legacyName as IconName : undefined);
            if (logical && !_resolvedIds[logical]) {
              _resolvedIds[logical] = id;
            }
          }
        }
      }
    }
  } catch {
    // Manifest not present or invalid — that's fine
  }
}

/** Normalize any EmojiName (legacy or new) to logical IconName */
function toLogical(name: EmojiName): IconName {
  if (name in LEGACY_TO_LOGICAL) {
    return LEGACY_TO_LOGICAL[name as LegacyEmojiName];
  }
  if (ICON_NAMES.includes(name as IconName)) {
    return name as IconName;
  }
  throw new Error(`Unknown emoji name: ${name}`);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Get a Discord custom emoji string, or Unicode fallback.
 *
 * Accepts both legacy "ash_*" names and new logical names.
 *
 * Usage in embeds / message content:
 *   const e = emoji("success");
 *   embed.setDescription(`${e} Operation completed`);
 *
 * Usage in select menus / buttons:
 *   .setEmoji(emoji("ai"))
 */
export function emoji(name: EmojiName): string {
  init();
  const logical = toLogical(name);
  const id = _resolvedIds[logical];
  const legacyName = `ash_${logical}` as LegacyEmojiName;
  if (id && _guildId) {
    return `<:${legacyName}:${id}>`;
  }
  return ICON_MAP[logical].fallback;
}

/**
 * Get just the emoji ID string (without Discord formatting).
 * Useful for programmatic access.
 */
export function emojiId(name: EmojiName): string | undefined {
  init();
  const logical = toLogical(name);
  return _resolvedIds[logical];
}

/**
 * Get the guild ID where custom emojis are uploaded.
 */
export function emojiGuildId(): string | undefined {
  init();
  return _guildId;
}

/**
 * Get the Unicode fallback for a given emoji name.
 */
export function unicodeFallback(name: EmojiName): string {
  const logical = toLogical(name);
  return ICON_MAP[logical].fallback;
}

/**
 * Check if custom emoji is configured for a given name.
 */
export function hasCustomEmoji(name: EmojiName): boolean {
  init();
  const logical = toLogical(name);
  return !!_resolvedIds[logical] && !!_guildId;
}

/**
 * Get all configured emoji names and their IDs.
 */
export function configuredEmojis(): Partial<Record<IconName, string>> {
  init();
  return { ..._resolvedIds };
}

/**
 * Get the path to the PNG asset for a given emoji name.
 * Returns undefined if the asset doesn't exist.
 */
export function emojiAssetPath(name: EmojiName): string | undefined {
  const logical = toLogical(name);
  const pngPath = join(process.cwd(), "assets", "emojis", "png", `ash_${logical}.png`);
  return existsSync(pngPath) ? pngPath : undefined;
}

/**
 * Get all available emoji PNG asset paths.
 */
export function allEmojiAssets(): Partial<Record<IconName, string>> {
  const result: Partial<Record<IconName, string>> = {};
  for (const name of ICON_NAMES) {
    result[name] = emojiAssetPath(name);
  }
  return result;
}

// ---------------------------------------------------------------------------
// Convenience getters for common patterns
// ---------------------------------------------------------------------------

/** Shorthand: success emoji */
export const E_SUCCESS = () => emoji("success");

/** Shorthand: error emoji */
export const E_ERROR = () => emoji("error");

/** Shorthand: warning emoji */
export const E_WARNING = () => emoji("warning");

/** Shorthand: info emoji */
export const E_INFO = () => emoji("info");

/** Shorthand: AI/robot emoji */
export const E_AI = () => emoji("ai");

/** Shorthand: loading emoji */
export const E_LOADING = () => emoji("loading");

/** Shorthand: online status */
export const E_ONLINE = () => emoji("online");

/** Shorthand: offline status */
export const E_OFFLINE = () => emoji("offline");

/** Shorthand: degraded status */
export const E_DEGRADED = () => emoji("degraded");

/** Shorthand: settings emoji */
export const E_SETTINGS = () => emoji("settings");

/** Shorthand: arrow emoji */
export const E_ARROW = () => emoji("arrow");

/** Shorthand: menu emoji */
export const E_MENU = () => emoji("menu");

/** Shorthand: refresh emoji */
export const E_REFRESH = () => emoji("refresh");

/** Shorthand: memory/brain emoji */
export const E_MEMORY = () => emoji("memory");

/** Shorthand: stats/chart emoji */
export const E_STATS = () => emoji("stats");

// ── Anime Emotion Emojis ──

/** Shorthand: thinking emoji */
export const E_THINK = () => emoji("think");

/** Shorthand: happy emoji */
export const E_HAPPY = () => emoji("happy");

/** Shorthand: sad emoji */
export const E_SAD = () => emoji("sad");

/** Shorthand: angry emoji */
export const E_ANGRY = () => emoji("angry");

/** Shorthand: confused emoji */
export const E_CONFUSED = () => emoji("confused");

/** Shorthand: shy emoji */
export const E_SHY = () => emoji("shy");

/** Shorthand: surprised emoji */
export const E_SURPRISED = () => emoji("surprised");

/** Shorthand: sleep emoji */
export const E_SLEEP = () => emoji("sleep");

/** Shorthand: focus emoji */
export const E_FOCUS = () => emoji("focus");

/** Shorthand: laugh emoji */
export const E_LAUGH = () => emoji("laugh");
