/* ================================================================
 * TOOL CONFIRMATION UI
 *
 * Renders the Confirm/Cancel button rows for AI action plans
 * (`ashen_tool_confirm:<planId>` / `ashen_tool_cancel:<planId>`).
 *
 * This is the production renderer consumed by index.ts when the
 * conversational agent returns requiresConfirmation=true. The
 * matching dispatcher lives in confirmation-handler.ts — both sides
 * share the prefix constants so they can never drift apart.
 *
 * Security notes:
 *   - planId is generated by createActionPlan (`plan_` + hex) and is
 *     only an opaque lookup key: the handler re-validates existence,
 *     expiry, requester binding, guild binding and double-execution
 *     before anything runs.
 *   - Malformed/oversized ids render NO buttons (fail closed) rather
 *     than emitting custom IDs the dispatcher could mis-slice.
 * ================================================================ */

import { ActionRowBuilder, ButtonBuilder, ButtonStyle } from "discord.js";
import { logger } from "../../logger";
import { CONFIRM_PREFIX, CANCEL_PREFIX } from "./confirmation-handler";
import {
  getPendingPlan,
  isPlanExpired,
  isPlanExecuted,
} from "../../ai/tools/confirmation-store";

/**
 * Discord caps custom_id at 50 characters.
 * Longest legitimate id today: `plan_` + 16 hex chars = 21.
 */
const MAX_PLAN_ID_LENGTH = 30;
const SAFE_PLAN_ID = /^[A-Za-z0-9_-]+$/;

/**
 * Build Confirm/Cancel button rows for a pending action plan.
 *
 * Returns NO buttons when the plan is missing, expired, already
 * executed, or the id is malformed — every rendered button is
 * guaranteed to resolve in the confirmation handler.
 */
export function buildToolConfirmationComponents(
  planId: string,
): ActionRowBuilder<ButtonBuilder>[] {
  if (
    typeof planId !== "string" ||
    planId.length === 0 ||
    planId.length > MAX_PLAN_ID_LENGTH ||
    !SAFE_PLAN_ID.test(planId)
  ) {
    logger.warn(
      `tool_confirmation_ui rejected invalid planId (len=${typeof planId === "string" ? planId.length : "non-string"})`,
    );
    return [];
  }

  const plan = getPendingPlan(planId);
  if (!plan) {
    logger.warn(`tool_confirmation_ui: plan ${planId} not pending — no buttons rendered.`);
    return [];
  }
  if (isPlanExpired(plan)) {
    logger.warn(`tool_confirmation_ui: plan ${planId} expired — no buttons rendered.`);
    return [];
  }
  if (isPlanExecuted(planId)) {
    logger.warn(`tool_confirmation_ui: plan ${planId} already executed — no buttons rendered.`);
    return [];
  }

  const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
    new ButtonBuilder()
      .setCustomId(`${CONFIRM_PREFIX}${planId}`)
      .setLabel("Confirm")
      .setStyle(ButtonStyle.Success),
    new ButtonBuilder()
      .setCustomId(`${CANCEL_PREFIX}${planId}`)
      .setLabel("Cancel")
      .setStyle(ButtonStyle.Danger),
  );

  return [row];
}
