server:
  port: ${PORT:2333}
  address: 0.0.0.0

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

    remoteCipher:
      url: "https://cipher.kikkia.dev/"
      userAgent: "AshenAI-Lavalink"

    clients:
      - ANDROID_VR
      - ANDROID_MUSIC
      - IOS
      - MWEB
      - WEB
      - WEBEMBEDDED
      - MUSIC

    clientOptions:
      ANDROID_VR:
        playback: true
        playlistLoading: true
        videoLoading: true
        searching: true

      ANDROID_MUSIC:
        playback: true
        playlistLoading: false
        videoLoading: true
        searching: true

      IOS:
        playback: true
        playlistLoading: true
        videoLoading: true
        searching: true

      MWEB:
        playback: true
        playlistLoading: true
        videoLoading: true
        searching: true

      WEB:
        playback: true
        playlistLoading: true
        videoLoading: true
        searching: true

      WEBEMBEDDED:
        playback: true
        playlistLoading: false
        videoLoading: true
        searching: false

      MUSIC:
        playback: false
        playlistLoading: false
        videoLoading: false
        searching: true

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false

  server:
    password: "ashenai-local"

    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false

    bufferDurationMs: 0
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    playerUpdateInterval: 5
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG
